name: coindeblend
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - scipy
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - seaborn
  - sep
  - Keras
  - tensorflow=1.14
  - astropy
  - scikit-learn
